### ISSUE TITLE
Placing Down Hat Stand Causes Crash

### ISSUE THREAD

**Issue by Fourbo** [fonnymunkey/SimpleHats#1]
Placing down a hat stand causes the game to crash, and when I try to join again I am unable to reenter the world afterwards. This was tested in a single player world.

**Version tested:** simplehats-fabric-1.18.2-0.1.0
**Fabric Loader:** 0.14.8
**Fabric API:** 0.56.1

**Comment by fonnymunkey** [comment]
Please upload the full crash-report file to a site like pastebin and link it here

**Comment by Fourbo** [comment]
Here's the link to the latest crash report:
https://gist.github.com/Fourbo/f2a6931c25394a449b6b4e0f20d8c662

If it helps too, this is the screen I got when the crash happened and after trying to rejoin.
![image](https://user-images.githubusercontent.com/101537906/175517625-71f53d7c-2cd1-48ed-a037-505b8d255e84.png)

**Comment by fonnymunkey** [comment]
Was able to find the issue, another mod not null checking, I should be able to fix it anyways and have a version uploaded soon.

**Comment by fonnymunkey** [comment]
0.1.1 is uploading to Curseforge, should fix this issue.
Note: I don't know if it'll automatically fix existing entities, you may need to remove the mod, load the world, then re-add it
(Forge has an option to automatically remove erroring entities instead, no idea if Fabric has a similar option)

**Comment by fonnymunkey** [comment]
Closing, assumed fixed.
