### ISSUE TITLE
Incompatibility with Continuity while loading resourcepacks

### ISSUE THREAD

**Issue by Foxsyl** [fonnymunkey/SimpleHats#10]
[latest.log](https://github.com/fonnymunkey/SimpleHats/files/9997370/latest.log)
i try disabling mod one by one but i still dont find what this couse

**Comment by Foxsyl** [comment]
i find that the mod continuity is causing this and now it start properly

**Comment by fonnymunkey** [comment]
The crash however does appear to possibly being caused by an incompatibility with Continuity, so I'll have to investigate further and hopefully fix it.

**Comment by fonnymunkey** [comment]
See above linked issue, missing Indium.
