### ISSUE TITLE
Getting kicked from server when opening bag, 1.19.2

### ISSUE THREAD

**Issue by quotabat** [fonnymunkey/SimpleHats#11]
I am getting kicked from server when I try to open a bag. This does not happen in single player. I am hosting the server and made the modpack. 

https://www.curseforge.com/minecraft/modpacks/homie-house-smp

https://youtu.be/Oc8-WP_n0TM

Attached a screenshot of the server log of me joining, holding right click on the bag, and getting kicked from the server.

I am somewhat new to hosting/creating my own modpack so I don't know how to read sever logs errors like this and don't know fully what to look for.

![image](https://user-images.githubusercontent.com/118788463/203215572-1d8f59d9-a0be-4c35-aded-52e523e3757c.png)

**Comment by fonnymunkey** [comment]
0.1.6 is being processed on CF currently, hopefully fixes this issue, reopen with a new crash report if it doesn't.

**Comment by quotabat** [comment]
Sounds good, will update server and modpack and see how it goes thanks!
