### ISSUE TITLE
Add to Modrinth

### ISSUE THREAD

**Issue by sylv256** [fonnymunkey/SimpleHats#12]
Please add this mod to Modrinth to make it easier for modpack creators etc. on Modrinth.
An increasing number of mods are moving to Modrinth, especially as they recently added monetization support. Modrinth is a platform with better searching, API, and features for mod developers, and their community and developers are very welcoming to developers.

**Comment by fonnymunkey** [comment]
(Under moderator review but will be at this link:) https://modrinth.com/mod/simple-hats
