### ISSUE TITLE
Clarify Modpack Usage

### ISSUE THREAD

**Issue by sylv256** [fonnymunkey/SimpleHats#13]
Please clarify if this mod can be used in modpacks, specifically in the `README.md`.

**Comment by sylv256** [comment]
especially because this mod's assets are ARR

**Comment by fonnymunkey** [comment]
As this mod is uploaded both to Curseforge and (pending) Modrinth, it can inherently be used in modpacks hosted on both of those sites following their own modpack rules.

As for rehosting elsewhere, ideally the person should ask either me, or more realistically ArtsyDy as it is their assets that are ARR.
