### ISSUE TITLE
grab bags work but hats don't

### ISSUE THREAD

**Issue by Toekeyo** [fonnymunkey/SimpleHats#15]
hey so me and my friend have this mod on our 1.19.3 server and the grab bags work but when you open them nothing drops you get air we even tried to spawn the hats in creative and we still got air it gives you nothing the hats show up through roughly enough items mod but we can't use them so if you could please fix this issue or tell us how it would be much appreciated.

**Comment by fonnymunkey** [comment]
Can you upload the server's log file and/or upload it to a site like pastebin and link it?

It sounds like the default hats are being loaded clientside, but the server isn't actually loading any hats.
Have you modified the hat json config at all? Maybe just needs to be deleted and regened.
