### ISSUE TITLE
Instruction custom hats

### ISSUE THREAD

**Issue by BoxingJoost** [fonnymunkey/SimpleHats#17]
Could you make an instruction video on how to add custom hats?

**Comment by fonnymunkey** [comment]
You can remove/add/edit any hat you want by modifying the SimpleHat's json file in the config folder.

If you want to add a new hat, all you need to do is create a new entry in the json file, you can simply just copy one of the other entries and rename it to whatever you want to name the new hat.

The hat models/textures are loaded like a normal resourcepack would be as a zip in the resourcepacks folder. Hat textures go in "pack/assets/simplehats/textures/item/hats/hatname.png", hat models go in "pack/assets/simplehats/models/item/hatname.json"
