### ISSUE TITLE
[Suggestion] Option to configure drop rate of grab-bags

### ISSUE THREAD

**Issue by MarioSMB** [fonnymunkey/SimpleHats#18]
It would be incredibly helpful to have an option in the configuration files to adjust the drop rate of grab-bags as they're too common at the moment, thanks!

**Comment by fonnymunkey** [comment]
Loot drop rates and conditions for both Forge and Fabric can and should be done with a Datapack:
(https://minecraft.fandom.com/wiki/Tutorials/Creating_a_data_pack)
Datapacks are very simple to use once you make your first one, and are critical for anyone on newer versions working with mods or modpacks to learn.
