### ISSUE TITLE
Doesn't Work on my 1.18.2 Server

### ISSUE THREAD

**Issue by Relaxing9** [fonnymunkey/SimpleHats#19]
Having SimpleHats on my server doesn't allow players to join due to mod version not matching even though they do...

Server Version: This server is running Magma version 1.18.2-6f06aa3a (Implementing API version 1.18.2-R0.1-SNAPSHOT, Forge Version 40.2.0)

![image](https://user-images.githubusercontent.com/41935047/215004681-d0ac0a7c-3311-4608-bc42-859ef98e75f3.png)

**Comment by fonnymunkey** [comment]
Is this a premade modpack, or a personal modpack/server?

If either the server or the client modified the simplehats.json file, and removed/added/renamed hats without the file being matched on both sides, that can cause a registry conflict.

Or if its a premade modpack, but either server or client did not properly install the configs, that could cause it as well.

If nothing else, could try redownloading the mod and reinstalling it on both sides, clearing the configs.

**Comment by Relaxing9** [comment]
Will look into it when I have the time. Thanks for the expedited response though. (I do hope it's that)

**Comment by Relaxing9** [comment]
Synced the configs and it fixed the issue thanks again for helping out.
