### ISSUE TITLE
OptiFabric incompatible Fabric API dependency version 

### ISSUE THREAD

**Issue by Kino0208** [fonnymunkey/SimpleHats#2]
- Mod 'SimpleHats' (simplehats) 1.18.2-0.1.0 requires version 0.55.1 or later of mod 'Fabric API' (fabric), but only the wrong version is present: 0.51.1+1.18.2!
But the renderer used by my fabric client is optifabric+optifine because their light and shadow frame performance is much better than other renderers. I don’t know if you will downgrade the requirement of mod to use fabric api to 0.51.1
Now optifabric+optifine only supports the 0.51.1 fabric api and does not support the latest version of the api
The bug is the inability to enter/create the world
[latest.log](https://github.com/fonnymunkey/SimpleHats/files/8973367/latest.log)

**Comment by fonnymunkey** [comment]
Ill see if I can lower the required version, no idea if it'll cause other random issues.

**Comment by fonnymunkey** [comment]
Unfortunately it seems the version of Fabric API that breaks compatibility with OptiFabric is a single version lower than a version with API methods I require for SimpleHats, so I can't lower the required version to work with OptiFabric.
OptiFabric will need to update and fix its incompatability with newer Fabric API versions.

However, if you are using OptiFabric+Optifine for performance, you should switch to using other mods https://gist.github.com/modmuss50/deff1658c4550ca8b16cb5d40ceaa468#Sodium as even stated on OptiFabric's page itself.

**Comment by fonnymunkey** [comment]
OptiFabric has released new versions that fix their incompatibility, it loads fine now with SimpleHats and updated Fabric API, closing as resolved.
