### ISSUE TITLE
[Request] Forge 1.20.1

### ISSUE THREAD

**Issue by realBritakee** [fonnymunkey/SimpleHats#28]
hey, are there any plans to update Simple Hats to forge 1.20/1.20.1 i would need it for my modpack

**Comment by fonnymunkey** [comment]
Forge has a bug in 1.20 and 1.20.1 that breaks the method to add hat bag drops to entities, so hat bags would only be obtainable from chests, and I wasn't planning on releasing the update until they fix it:
https://github.com/MinecraftForge/MinecraftForge/issues/9551

**Comment by fonnymunkey** [comment]
I've uploaded both 1.20 and 1.20.1 Fabric/Forge to Curseforge/Modrinth as I don't see this bug getting fixed in the near future, so people will just have to deal with entities not dropping hat bags until its fixed.
