### ISSUE TITLE
Unable to join a world 1.19

### ISSUE THREAD

**Issue by iiKey** [fonnymunkey/SimpleHats#3]
[latest.log](https://github.com/fonnymunkey/SimpleHats/files/9111129/latest.log)

Fabric Mods: 
		advancementinfo: AdvancementInfo 1.19-fabric0.53.3-1.3.1
		advancementplaques: Advancement Plaques 1.4.5
		another_furniture: Another Furniture 2.0.1-1.19
		architectury: Architectury 5.9.30
		auditory: Auditory 0.0.2-1.19
		awesomedungeon: Awesome Dungeon 2.0.9
		balm-fabric: Balm 4.3.0+0
		betterf3: BetterF3 1.3.1
		betterfpsdist: Better FPS distance Mod 1.19-1.9
		betterpingdisplay: Better Ping Display 1.1.1
		bettervillage: Better Village 1.0.1
		bigbeacons: Big Beacons 1.2.6
		biomemakeover: Biome Makeover 1.19-1.5.8
		bobby: Bobby 4.0.0
			com_typesafe_config: config 1.4.2
			fabric-api-base: Fabric API Base 0.4.9+e62f51a3a9
			io_leangen_geantyref_geantyref: geantyref 1.3.13
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		chat_heads: Chat Heads 0.6.0
		chisel: Chisel Refabricated 1.4.6
		chorus_links: Chorus Links 1.5.0
		cloth-config: Cloth Config v6 7.0.73
			cloth-basic-math: cloth-basic-math 0.6.1
		collective-fabric: Collective (Fabric) 4.27
			fiber: fiber 0.23.0-2
		continuity: Continuity 2.0.0+1.19
		crawl: Crawl 0.11.0
			mm: Manningham Mills 2.3
		croptopia: Croptopia 2.0.7
		dashloader: DashLoader 4.0.0+1.19
			com_github_luben_zstd-jni: zstd-jni 1.5.2-2
			dev_quantumfusion_hyphen: Hyphen 0.2.2
			dev_quantumfusion_taski: Taski 1.1.0
		doggomod: Doggo Mod 1.2.0
		dual_riders: Dual Riders 1.1.2
		eatinganimationid: Eating Animation 1.8.1
		ecologics: Ecologics 2.1.3
		emojitype: Emoji Type 2.0.0+1.19
		emotecraft: Emotecraft 2.1.3-SNAPSHOT-build.30
			bendy-lib: Bendy api 2.0.4
		enderitemod: Enderite Mod 1.4.1
		exlinedoors: Exline's Doors 2.3.5
		extrasounds: ExtraSounds 2.3.1+1.19
		advanced_runtime_resource_pack: Runtime Resource Pack 0.6.2
			soundcategories: Sound Categories 1.2.4+1.19
		fabric: Fabric API 0.57.0+1.19

**Comment by fonnymunkey** [comment]
You have a ton of errors from other mods/issues but I see nothing in that log pointing to SimpleHats being the problem.

**Comment by iiKey** [comment]
I checked it by deleting this mod and launching the game. Wish to play this
mod

чт, 14 июл. 2022 г. в 21:41, fonnymunkey ***@***.***>:

**Comment by fonnymunkey** [comment]
0.1.3 has been uploaded for all versions, try deleting previous files and updating.
If the issue continues, make a new issue report with a crash-log.
The linked log has no further useful information pertaining to Simple Hats, just other mods erroring.
