### ISSUE TITLE
FML 47.1.0 Overflow crash when mob drop

### ISSUE THREAD

**Issue by SirRosenfeld** [fonnymunkey/SimpleHats#32]
World host (client or server) crashes when trying to generate loottable after killing a mob.

Forge 47.1.0
Minecraft 1.20.1
SimpleHats 0.2.0

Tested when killing a skeleton
100% success rate

crashlog : https://pastebin.com/MddSyxJQ

**Comment by fonnymunkey** [comment]
This is caused by the latest Forge update, they fixed entity loot table modifiers not working at all, but in doing so broke SimpleHats method.
0.2.1 is uploading to Curseforge/Modrinth now which should fix this.
