### ISSUE TITLE
[Question] About porting to Forge 1.16.5

### ISSUE THREAD

**Issue by KLjiana** [fonnymunkey/SimpleHats#37]
I'm interested in this mod and want to play it in 1.16.5Forge. But I don't know Java. As an author, can you port it to 1.16.5Forge? Thanks.

**Comment by fonnymunkey** [comment]
I have no interest in porting to versions pre 1.18, but the mod is open source, people are free to contribute if they want to backport.

**Comment by KLjiana** [comment]
Ok, I see, thanks for the reply
