### ISSUE TITLE
Doesnt work on 1.20.1 (Forge)

### ISSUE THREAD

**Issue by WidowDt** [fonnymunkey/SimpleHats#39]
The hats don't go on any slots in the new version? I've tired every hat in every slot and it will just not work.

**Comment by fonnymunkey** [comment]
They go in the hat slot in the Curios menu, either click the Curio button in the top left of the player portrait in the inventory, or the default keybind is "G".

**Comment by ghost** [comment]
Sadly, I'm facing the same problem; it's not possible to equip a hat in the new version. Here's a short video.
![simple hats](https://github.com/fonnymunkey/SimpleHats/assets/93146402/c6e9677b-c78c-4aa4-961a-f7c0dda46df4)

**Comment by fonnymunkey** [comment]
The latest version of Curios uploaded a day ago broke compat with SimpleHats, downgrade to Curios 5.2.0-beta.3 for now until I can upload a fix.

**Comment by ghost** [comment]
Thanks, it is working now.

**Comment by WidowDt** [comment]
thank you, hopefully you all will get it updated and working soon :)

**Comment by fonnymunkey** [comment]
Fixed as of SimpleHats Forge 0.2.2.
