### ISSUE TITLE
"Failed to load correctly" Error on launch

### ISSUE THREAD

**Issue by mimi-min** [fonnymunkey/SimpleHats#4]
This mod looks so fun, but unfortunately I can't get MC to run properly with it :c 

Crash log: https://pastebin.com/L8sbRTBD

**Comment by fonnymunkey** [comment]
Apparently Forge recently had a breaking update, which is what is causing this. If you want to play right now, you can try downgrading Forge (Pre 41.1 should work I believe), otherwise you'll have to wait a little bit while I get a new version fixed and built.

**Comment by mimi-min** [comment]
Thank you for your quick response!

Ah, I recall another mod having the same issue... and when I tried downgrading a bunch of other mods broke, so I guess it's waiting for me.

Thanks again!

**Comment by fonnymunkey** [comment]
0.1.3 has been uploaded for all versions which should fix this issue.
