### ISSUE TITLE
Can't equip any hats. 1.20 

### ISSUE THREAD

**Issue by mipha120** [fonnymunkey/SimpleHats#44]
I can't equip the hats, I got the requirements on the website (The mods)

When I try to put it into the slot I am not able to.

**Comment by fonnymunkey** [comment]
What mod loader?
What version of SimpleHats?
What version of Curios or Trinkets?
If you're trying to put them in the helmet slot instead of the Curios/Trinkets slots, you need to enable that in the config.

**Comment by mipha120** [comment]
I am using Forge Minecraft as launcher, as for the version I am using the newest for 1.20. I am using Curios 5.3.5+1.20.1,

It doesnt work in the cosmetics slot either.

Also, I am using it on an aternos server but it isnt working in singleplayer either

**Comment by fonnymunkey** [comment]
The newest for 1.20 is not meant to work with Curios 1.20.1, you need to update SimpleHats to 1.20.1-0.2.2

**Comment by fonnymunkey** [comment]
Closing as assumed resolved.
