### ISSUE TITLE
There is a typo in the code name of the Dangersque Shades.

### ISSUE THREAD

**Issue by citric-sulfur** [fonnymunkey/SimpleHats#46]
![javaw_0YmPjB94eG](https://github.com/fonnymunkey/SimpleHats/assets/58549979/9dd9ab28-d415-44c3-827c-6b73504bfae8)

It says "dangereqsue"

**Comment by fonnymunkey** [comment]
The display name for this hat is correct which is what matters, the id is misspelled but if I changed it now it would cause registry errors in existing worlds so I do not plan on changing it.
