### ISSUE TITLE
[1.20.1] Incompatibility with Crawl Mod

### ISSUE THREAD

**Issue by Sheggs2** [fonnymunkey/SimpleHats#48]
The hats aren't anchored correctly with custom animations such as this mod that adds a dedicated crawling hotkey, not moving with the plays head properly. It works with the vanilla swimming animation however.
![2024-01-11_00 50 26](https://github.com/fonnymunkey/SimpleHats/assets/152367937/d804559c-3a21-4d90-8b68-0fba77bee2c6)
![2024-01-11_00 50 48](https://github.com/fonnymunkey/SimpleHats/assets/152367937/c03814b7-e91c-40d2-a6ba-a5d6ef2e71ac)

**Comment by fonnymunkey** [comment]
While I didn't test specifically with the Crawl mod, I did test with multiple other similar working animation mods, this should be fixed as of 0.3.1, if it continues to be an issue create a new post.
