### ISSUE TITLE
hat idea

### ISSUE THREAD

**Issue by AnomalousDeity** [fonnymunkey/SimpleHats#5]
Conical straw hat, maybe as a different variant to the farmer's brim?

**Comment by fonnymunkey** [comment]
We may end up doing an expansion pack of sorts to add a new set of hats, but that probably won't be for awhile. Currently the intention is players are able to add their own hats and models using the config system.

**Comment by BoxingJoost** [comment]
> We may end up doing an expansion pack of sorts to add a new set of hats, but that probably won't be for awhile. Currently the intention is players are able to add their own hats and models using the config system.

And how do we add those custom hats in? Could you make a clear instruction video for it?

**Comment by fonnymunkey** [comment]
You can remove/add/edit any hat you want by modifying the SimpleHat's json file in the config folder.

If you want to add a new hat, all you need to do is create a new entry in the json file, you can simply just copy one of the other entries and rename it to whatever you want to name the new hat.

The hat models/textures are loaded like a normal resourcepack would be as a zip in the resourcepacks folder. Hat textures go in "pack/assets/simplehats/textures/item/hats/hatname.png", hat models go in "pack/assets/simplehats/models/item/hatname.json"
