### ISSUE TITLE
cannot see the cosmetics bar on server

### ISSUE THREAD

**Issue by chopper355** [fonnymunkey/SimpleHats#52]
when i open this server i was able to use these mods features but then when i added other mods i cannot open the cosmetics bar but this only happens in the server.
i am able to see cosmetics bar on singleplayer and i dont why this happens.
its so weird i also tried to use other simplehat versions but nothing changed.
i was using this version simplehats-forge-1.18.2-0.2.3.jar 
then i tried to use these simplehats-forge-1.18.2-0.2.0.jar
simplehats-forge-1.18.2-0.1.6.jar (and using currently curios-forge-1.18.2-5.0.9.2.jar this curios version which is the last one for 1.18.2) but it didnt work maybe its not your fault but do you guys have any idea how can i fix that because this happens only when im on the server.
i really liked your mod and i want to use it.
i hope you guys have any idea to fix this thing.

**Comment by fonnymunkey** [comment]
If SimpleHats and Curios were working fine, then you added mods and it stopped working, start by removing the added mods until you figure out which one is causing the issue.
Cosmetic slots are handled by Curios, not SimpleHats, if they are not showing up it is likely whatever mod you added conflicting with Curios.

**Comment by fonnymunkey** [comment]
Closing as no response.
