### ISSUE TITLE
No Way to Edit Drop Rate

### ISSUE THREAD

**Issue by MrJJLand** [fonnymunkey/SimpleHats#53]
Started using the mod for a private server, and while the hat drops were unique and fun at first, we quickly became overwhelmed with the sheer amount of bags we had when we had most of them already.
I went to edit the amount in the .toml common or client file, but there is not a place to make this edit. The .json file also does not have a place for this, just the weight of specific hats.
Can we get a way to edit their drop rates?

**Comment by fonnymunkey** [comment]
If you are playing on Fabric, there are options in the config, if you are playing on Forge, you can use a Datapack to modify the loot tables.
Pre-made examples for the Datapacks are provided on my discord linked on the Curseforge mod page if you don't know how to set up your own.
