### ISSUE TITLE
[1.20.1 Forge] Game crash upon looking at a hat's tooltip

### ISSUE THREAD

**Issue by BylethTheCrafter** [fonnymunkey/SimpleHats#56]
When attempting to look at the tooltip for a hat, the game crashes instantly.

Forge Version: 47.2.23
Curios API Version: 5.8.0+1.20.1
Simple Hats Version: 1.20.1-0.2.2

Log: https://hastebin.com/share/vayiziwenu.bash
Crash Report: https://hastebin.com/share/uwehiragiw.perl

**Comment by fonnymunkey** [comment]
Curios just updated today and it broke compatibility, I'll work on publishing a fix, in the meantime you can downgrade Curios to the previous release version to keep playing.

**Comment by Luktasclip** [comment]
I have the same bug and the curiosAPI version is 5.8.0
[crash-2024-04-19_23.40.01-client.txt](https://github.com/fonnymunkey/SimpleHats/files/15046723/crash-2024-04-19_23.40.01-client.txt)

**Comment by Luktasclip** [comment]
I have the same bug and the version is 5.8.0

**Comment by fonnymunkey** [comment]
Resolved in 0b422b4
