### ISSUE TITLE
issue with "baby turtle hat", blacklisted by JEI? 1.20.1 forge

### ISSUE THREAD

**Issue by Weether1** [fonnymunkey/SimpleHats#57]
[latest.log](https://github.com/fonnymunkey/SimpleHats/files/14984331/latest.log)

when i'd get in a world and check my JEI tab every item would say "tooltip error, see logs", so I went to look at what the issue was and it said something about the baby turtle hat being blacklisted by JEI?

**Comment by fonnymunkey** [comment]
"mods/simplehats-forge-1.20.1-0.2.2.jar.disabled" You disabled SimpleHats in the Curseforge launcher, that is why it is erroring, it didn't load.

**Comment by fonnymunkey** [comment]
Closed as assumed resolved.
