### ISSUE TITLE
issue connecting to a server

### ISSUE THREAD

**Issue by sodalicquor** [fonnymunkey/SimpleHats#58]
everytime i try to enter my server it appears this message: 
this issue is only happening to me, the server is working fine for other people, idk what to do

[latest (1).log](https://github.com/fonnymunkey/SimpleHats/files/14986102/latest.1.log)
![imagem_2024-04-15_230103253](https://github.com/fonnymunkey/SimpleHats/assets/167153233/a989a983-177c-406f-97d5-9ffd99453e9f)

**Comment by fonnymunkey** [comment]
SimpleHats version 0.2.0 added 30+ new hats, you needed to delete your old simplehats.json to regenerate it to get the new hats.

Delete the old simplehats.json file in the config folder and allow it to regenerate to get the new hats and resolve the error.
