### ISSUE TITLE
Glasses "Hats" Don't always cover eyes properly on MC Skins

### ISSUE THREAD

**Issue by ProWil** [fonnymunkey/SimpleHats#6]
This is an issue which could be easily fixed simply by adding a slider which allows you to adjust the y level a hat is on. Such a slider would make the glasses appear higher on the face when increased, and lower when decreased. I attempted to fix the issue myself by modifying the texture file to make the glasses higher, however, there were no texture files available for me to modify apart from one titled "special" which has nothing to do with glasses. Thanks for reading! Keep up the great work I would love to see this fixed!  :D

![not_aligned_with_eyes](https://user-images.githubusercontent.com/110945309/183779082-2fd2e70a-91f4-4e14-b9cd-772750275918.png)

**Comment by fonnymunkey** [comment]
Theoretically possible, I may add it in with the next update as I have to patch some issues with Forge anyways. I'll look into doing it on a per-hat basis so different hats can have different offsets and multiplayer will render the individual's settings, but I'm unsure if it'll work well, if anything I may just add a general config setting for offset that can be changed whenever.

**Comment by fonnymunkey** [comment]
I added a config option to adjust hat Y offset in all the latest versions, I may rework it later to be on a per-hat basis instead of all-at-once, but for now its working.
