### ISSUE TITLE
Issue with equipping?

### ISSUE THREAD

**Issue by lilacvalleys** [fonnymunkey/SimpleHats#62]
All the hats are showing in creative mode but I can't equip any of them

**Comment by fonnymunkey** [comment]
What game version? What mod version? Fabric or Forge? Upload your latest.log file from the logs folder.

**Comment by lilacvalleys** [comment]
1.20, downloaded "simplehats-forge-1.20-0.2.0.jar", can upload logs in a bit. Basically-- I can see every hat but they are useless, I cant do anything with them

**Comment by fonnymunkey** [comment]
1.20.0 is outdated and unsupported, update to either 1.20.1 or 1.20.4.
Curios updated and broke compat, the 1.20.1 and 1.20.4 versions have fixes for this.

**Comment by lilacvalleys** [comment]
if i update will i lose my builds though

**Comment by fonnymunkey** [comment]
Make a backup of your world then update and see, 1.20.0 worlds should be fine updating to 1.20.1.
You can look up guides for updating your game.
