### ISSUE TITLE
Simplehats requires "curios"

### ISSUE THREAD

**Issue by Evilunu** [fonnymunkey/SimpleHats#64]
Simplehats (forge version) requires "curios" i downloaded it and keep saying it... https://imgur.com/a/sVL5iho

**Comment by fonnymunkey** [comment]
Upload the latest.log from your logs folder.

**Comment by Evilunu** [comment]
[latest.log](https://github.com/fonnymunkey/SimpleHats/files/15099918/latest.log)

**Comment by fonnymunkey** [comment]
SimpleHats 1.20.4 0.2.4 requires Curios 7.4.0+, try updating to Curios 7.4.0-beta.2
If you still get the same message, it may be an issue with the Curios file itself, or your mod installation setup, since it is not seeing Curios as a valid mod.

**Comment by Evilunu** [comment]
![image](https://github.com/fonnymunkey/SimpleHats/assets/168007043/1bfc7608-b139-4045-a3d8-1d1502ff8aa9)
[latest.log](https://github.com/fonnymunkey/SimpleHats/files/15101494/latest.log)
Same message... I'll try to install forge again and try only simplehats and curios.

Edit: Nothing happend... Same error! I installed new forge version and like 3 or 4 differents versions of Curios (Curios 7.4.0-beta, beta2 and 7.3 versions)

**Comment by Evilunu** [comment]
News!! I installed older version of Forge (49.0.14) + Curios 7.3.4 + Simplehats 0.2.3 and now works!

**Comment by fonnymunkey** [comment]
I believe Curios is a multiloader mod, and one of the more recent Forge updates was related to multiloader jars, so its possible one of the latest Forge updates broke Curio loading.
Theoretically if its just a Forge issue then using the older Forge version along with Curios 7.4.0-beta.2 and SimpleHats 0.2.4 should work fine.
