### ISSUE TITLE
Hats Disappearing when trying to open any menus

### ISSUE THREAD

**Issue by BloodReddSky** [fonnymunkey/SimpleHats#66]
Whenever I try to open the crafting table for dying a hat, the hat i want to dye will vanish from my inventory, this also happens whenever i put the hat ontop of an already filled slot.

**Comment by fonnymunkey** [comment]
Can you upload the latest.log file from the logs folder from when this happens

**Comment by BloodReddSky** [comment]
Where would I find that?

**Comment by fonnymunkey** [comment]
In the logs folder in your modpack directory, its regenerated everytime you launch the game so launch the game, try dying a hat, close the game, then upload it.

**Comment by BloodReddSky** [comment]
this is only happening in multiplayer, I've tried it in singleplayer and I can dye hats, and I also currently cant get my own to work and dont have any friends online so, I won't beable to at the moment.

**Comment by fonnymunkey** [comment]
Closed as no response.
