### ISSUE TITLE
Incompatible versions in Mohist

### ISSUE THREAD

**Issue by Fallenbox233** [fonnymunkey/SimpleHats#67]
I once successfully loaded your Simple Hat mod on a 1.19.2 Fabric server.
However, after I use the Mohist server, the module loads and displays normally on the client, but every time I connect, the incompatible version is displayed, how can I solve this problem?
My friends and I really enjoyed this mod and they had a lot of fun with the old version of the server. We'd all appreciate it if you could help me with this tough problem.
<img width="1280" alt="805CFE765B4661775070B98613007B88" src="https://github.com/fonnymunkey/SimpleHats/assets/162810881/00afe85d-4656-4b43-8b60-469146d5105b">

**Comment by fonnymunkey** [comment]
When you update Simplehats to a version that adds new hats, you need to reset simplehats.json in the config folder to allow the new hats to generate.
The changelog warns about this, you need to do it on both server and client, if you made any custom changes copy them out and repaste them back after resetting the file.
That error means either the server or client has hats the other doesn't have.

**Comment by Fallenbox233** [comment]
ok thank you
