### ISSUE TITLE
Not connecting to server

### ISSUE THREAD

**Issue by ZentrixiExo** [fonnymunkey/SimpleHats#68]
Ive been trying to join a server, ive deleted the .json file and even the folder. Ive even deleted my entire minecraft folder and yet it still says this. Any help would be nice T -T
![image](https://github.com/fonnymunkey/SimpleHats/assets/172331066/bbe05b56-2dbd-4fce-baea-df27beb747eb)

**Comment by fonnymunkey** [comment]
When updating SimpleHats, both the server and client need to regenerate the simplehats.json file.

If you deleted it and you still get the error, that means the server either has not regenerated the file, or are still on a different version of SimpleHats.

If you're playing a modpack that has a customized file, wait for the modpack developer to update the files themselves

**Comment by ZentrixiExo** [comment]
oh i see, thank you! hadnt tried on the server end T _T

**Comment by fonnymunkey** [comment]
Closed as resolved.
