### ISSUE TITLE
simple hats encountered an error during the common_setup event phase

### ISSUE THREAD

**Issue by Papu010101100** [fonnymunkey/SimpleHats#78]
I was playing a modpack: https://legacy.curseforge.com/minecraft/modpacks/lovernite-adventure-1 , and i add simple hats cause i love it, but i was going to open it, its appears this message 
![imagen_2024-07-19_232514427](https://github.com/user-attachments/assets/e72ae6c2-833c-42e2-b90e-35884401be78)

Crash Report or Log
---- Minecraft Crash Report ---- // Hi. I'm Minecraft, and I'm a crashaholic. Time: 2024-07-19 22:46:20 Description: Mod loading error has occurred java.lang.Exception: Mod Loading has failed at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:60) ~[forge-1.20.1-47.2.21-universal.jar%23287!/:?] {re:classloading} at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:143) ~[forge-1.20.1-47.2.21-universal.jar%23287!/:?] {re:classloading,pl:runtimedistcleaner:A} at net.minecraft.client.Minecraft.lambda$new$4(Minecraft.java:571) ~[client-1.20.1-20230612.114412-srg.jar%23282!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A} at net.minecraft.Util.m_137521_(Util.java:421) ~[client-1.20.1-20230612.114412-srg.jar%23282!/:?] {re:classloading,re:mixin} at net.minecraft.client.Minecraft.lambda$new$5(Minecraft.java:564) ~[client-1.20.1-20230612.114412-srg.jar%23282!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A} at net.minecraftforge.client.loading.ForgeLoadingOverlay.m_88315_(ForgeLoadingOverlay.java:146) ~[forge-1.20.1-47.2.21-universal.jar%23287!/:?] {re:classloading} at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:954) ~[client-1.20.1-20230612.114412-srg.jar%23282!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A} at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23282!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A} at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23282!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A} at net.minecraft.client.main.Main.main(Main.java:218) ~[forge-47.2.21.jar:?] {re:classloading,pl:runtimedistcleaner:A} at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {} at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {} at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {} at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {} at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.21.jar:?] {} at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.21.jar:?] {} at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.21.jar:?] {} at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {} at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {} at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {} at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {} at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {} at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {} at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {} at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {} A detailed walkthrough of the error, its code path and all known details is as follows: --------------------------------------------------------------------------------------- -- Head -- Thread: Render thread Suspected Mod: SimpleHats (simplehats), Version: 1.20.1-0.3.0 Issue tracker URL: https://github.com/fonnymunkey/SimpleHats/issues at TRANSFORMER/simplehats@1.20.1-0.3.0/fonnymunkey.simplehats.SimpleHats.commonSetup(SimpleHats.java:50) Stacktrace: at fonnymunkey.simplehats.SimpleHats.commonSetup(SimpleHats.java:50) ~[simplehats-forge-1.20.1-0.3.0.jar%23272!/:1.20.1-0.3.0] {re:classloading} -- MOD simplehats -- Details: Mod File: /C:/Users/manda/curseforge/minecraft/Instances/LOVERNITE ADVENTURE 1.2/mods/simplehats-forge-1.20.1-0.3.0.jar Failure message: SimpleHats (simplehats) encountered an error during the common_setup event phase java.lang.NoSuchMethodError: 'void top.theillusivec4.curios.api.CuriosApi.registerCurioPredicate(net.minecraft.resources.ResourceLocation, java.util.function.Predicate)' Mod Version: 1.20.1-0.3.0 Mod Issue URL: https://github.com/fonnymunkey/SimpleHats/issues Exception message: java.lang.NoSuchMethodError: 'void top.theillusivec4.curios.api.CuriosApi.registerCurioPredicate(net.minecraft.resources.ResourceLocation, java.util.function.Predicate)' Stacktrace: at fonnymunkey.simplehats.SimpleHats.commonSetup(SimpleHats.java:50) ~[simplehats-forge-1.20.1-0.3.0.jar%23272!/:1.20.1-0.3.0] {re:classloading} at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.5.jar%2387!/:?] {} at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.5.jar%2387!/:?] {} at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2387!/:?] {} at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2387!/:?] {} at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:114) ~[javafmllanguage-1.20.1-47.2.21.jar%23284!/:?] {} at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:125) ~[fmlcore-1.20.1-47.2.21.jar%23283!/:?] {} at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {} at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {} at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {} at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {} at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {} at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {} at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {} -- System Details -- Details: Minecraft Version: 1.20.1 Minecraft Version ID: 1.20.1 Operating System: Windows 10 (amd64) version 10.0 Java Version: 17.0.8, Microsoft Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft Memory: 761264128 bytes (725 MiB) / 3112173568 bytes (2968 MiB) up to 4294967296 bytes (4096 MiB) CPUs: 12 Processor Vendor: GenuineIntel Processor Name: 12th Gen Intel(R) Core(TM) i5-12400 Identifier: Intel64 Family 6 Model 151 Stepping 5 Microarchitecture: Alder Lake Frequency (GHz): 2.50 Number of physical packages: 1 Number of physical CPUs: 6 Number of logical CPUs: 12 Graphics card #0 name: Intel(R) UHD Graphics 730 Graphics card #0 vendor: Intel Corporation (0x8086) Graphics card #0 VRAM (MB): 128.00 Graphics card #0 deviceId: 0x4692 Graphics card #0 versionInfo: DriverVersion=31.0.101.5535 Graphics card https://github.com/Creators-of-Create/Create/issues/1 name: NVIDIA GeForce RTX 2060 Graphics card https://github.com/Creators-of-Create/Create/issues/1 vendor: NVIDIA (0x10de) Graphics card https://github.com/Creators-of-Create/Create/issues/1 VRAM (MB): 4095.00 Graphics card https://github.com/Creators-of-Create/Create/issues/1 deviceId: 0x1f03 Graphics card https://github.com/Creators-of-Create/Create/issues/1 versionInfo: DriverVersion=31.0.15.4633 Memory slot #0 capacity (MB): 8192.00 Memory slot #0 clockSpeed (GHz): 3.20 Memory slot #0 type: DDR4 Memory slot https://github.com/Creators-of-Create/Create/issues/1 capacity (MB): 8192.00 Memory slot https://github.com/Creators-of-Create/Create/issues/1 clockSpeed (GHz): 3.20 Memory slot https://github.com/Creators-of-Create/Create/issues/1 type: DDR4 Virtual memory max (MB): 25903.87 Virtual memory used (MB): 18946.96 Swap memory total (MB): 9728.00 Swap memory used (MB): 650.99 JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m Loaded Shaderpack: ComplementaryReimagined_r1.2.2.zip Profile: HIGH (+0 options changed by user) ModLauncher: 10.0.9+10.0.9+main.dcd20f30 ModLauncher launch target: forgeclient ModLauncher naming: srg ModLauncher services: mixin-0.8.5.jar mixin PLUGINSERVICE eventbus-6.0.5.jar eventbus PLUGINSERVICE fmlloader-1.20.1-47.2.21.jar slf4jfixer PLUGINSERVICE fmlloader-1.20.1-47.2.21.jar object_holder_definalize PLUGINSERVICE fmlloader-1.20.1-47.2.21.jar runtime_enum_extender PLUGINSERVICE fmlloader-1.20.1-47.2.21.jar capability_token_subclass PLUGINSERVICE accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE fmlloader-1.20.1-47.2.21.jar runtimedistcleaner PLUGINSERVICE modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE FML Language Providers: minecraft@1.0 lowcodefml@null javafml@null Mod List: TreeChop-1.20.1-forge-0.19.0.jar |HT's TreeChop |treechop |0.18.8 |SIDED_SETU|Manifest: NOSIGNATURE geckolib-forge-1.20.1-4.4.2.jar |GeckoLib 4 |geckolib |4.4.2 |SIDED_SETU|Manifest: NOSIGNATURE beautify-2.0.2.jar |Beautify |beautify |2.0.2 |SIDED_SETU|Manifest: NOSIGNATURE jei-1.20.1-forge-15.3.0.4.jar |Just Enough Items |jei |15.3.0.4 |SIDED_SETU|Manifest: NOSIGNATURE libraryferret-forge-1.20.1-4.0.0.jar |Library ferret |libraryferret |4.0.0 |SIDED_SETU|Manifest: NOSIGNATURE mcw-windows-2.2.1-mc1.20.1forge.jar |Macaw's Windows |mcwwindows |2.2.1 |SIDED_SETU|Manifest: NOSIGNATURE gnumus_settlement_[Forge]1.20.1_v1.0.jar |Gnumus Settlement |gnumus |1.0.0 |SIDED_SETU|Manifest: NOSIGNATURE sophisticatedcore-1.20.1-0.6.8.567.jar |Sophisticated Core |sophisticatedcore |0.6.8.567 |SIDED_SETU|Manifest: NOSIGNATURE rubidium-mc1.20.1-0.7.1a.jar |Rubidium |rubidium |0.7.1a |SIDED_SETU|Manifest: NOSIGNATURE waystones-forge-1.20-14.1.3.jar |Waystones |waystones |14.1.3 |SIDED_SETU|Manifest: NOSIGNATURE journeymap-1.20.1-5.9.18p1-forge.jar |Journeymap |journeymap |5.9.18p1 |SIDED_SETU|Manifest: NOSIGNATURE citadel-2.5.4-1.20.1.jar |Citadel |citadel |2.5.4 |SIDED_SETU|Manifest: NOSIGNATURE alexsmobs-1.22.8.jar |Alex's Mobs |alexsmobs |1.22.8 |SIDED_SETU|Manifest: NOSIGNATURE NaturesCompass-1.20.1-1.11.2-forge.jar |Nature's Compass |naturescompass |1.20.1-1.11.2-forge |SIDED_SETU|Manifest: NOSIGNATURE artifacts-forge-9.3.0.jar |Artifacts |artifacts |9.3.0 |SIDED_SETU|Manifest: NOSIGNATURE mixinextras-forge-0.2.0-beta.9.jar |MixinExtras |mixinextras |0.2.0-beta.9 |SIDED_SETU|Manifest: NOSIGNATURE sophisticatedbackpacks-1.20.1-3.20.2.1022.jar |Sophisticated Backpacks |sophisticatedbackpacks |3.20.2.1022 |SIDED_SETU|Manifest: NOSIGNATURE ExplorersCompass-1.20.1-1.3.3-forge.jar |Explorer's Compass |explorerscompass |1.20.1-1.3.3-forge |SIDED_SETU|Manifest: NOSIGNATURE balm-forge-1.20.1-7.2.2.jar |Balm |balm |7.2.2 |SIDED_SETU|Manifest: NOSIGNATURE watut-forge-1.20.1-1.1.0.jar |What Are They Up To |watut |1.20.1-1.1.0 |SIDED_SETU|Manifest: NOSIGNATURE cloth-config-11.1.118-forge.jar |Cloth Config v10 API |cloth_config |11.1.118 |SIDED_SETU|Manifest: NOSIGNATURE forge-1.20.1-47.2.21-universal.jar |Forge |forge |47.2.21 |SIDED_SETU|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90 MOAdecor BATH 1.20.1.jar |MOA DECOR: BATH |moa_decor_bath |1.20.1 |SIDED_SETU|Manifest: NOSIGNATURE konkrete_forge_1.8.0_MC_1.20-1.20.1.jar |Konkrete |konkrete |1.8.0 |SIDED_SETU|Manifest: NOSIGNATURE client-1.20.1-20230612.114412-srg.jar |Minecraft |minecraft |1.20.1 |SIDED_SETU|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f mcw-bridges-2.1.1-mc1.20.1forge.jar |Macaw's Bridges |mcwbridges |2.1.1 |SIDED_SETU|Manifest: NOSIGNATURE FarmersDelight-1.20.1-1.2.4.jar |Farmer's Delight |farmersdelight |1.20.1-1.2.4 |SIDED_SETU|Manifest: NOSIGNATURE vanillaplustools-1.20-1.0.jar |Vanilla+ Tools |vanillaplustools |1.20-1.0 |SIDED_SETU|Manifest: NOSIGNATURE torchmaster-20.1.5.jar |Torchmaster |torchmaster |20.1.5 |SIDED_SETU|Manifest: NOSIGNATURE handcrafted-forge-1.20.1-3.0.6.jar |Handcrafted |handcrafted |3.0.6 |SIDED_SETU|Manifest: NOSIGNATURE alexscaves-1.1.4.jar |Alex's Caves |alexscaves |1.1.4 |SIDED_SETU|Manifest: NOSIGNATURE TerraBlender-forge-1.20.1-3.0.1.4.jar |TerraBlender |terrablender |3.0.1.4 |SIDED_SETU|Manifest: NOSIGNATURE CozyHome-2.2.8-1.20.1.jar |Cozy Home |cozy_home |1.0.0 |SIDED_SETU|Manifest: NOSIGNATURE BiomesOPlenty-1.20.1-18.0.0.598.jar |Biomes O' Plenty |biomesoplenty |18.0.0.598 |SIDED_SETU|Manifest: NOSIGNATURE Jade-1.20.1-forge-11.9.2.jar |Jade |jade |11.9.2+forge |SIDED_SETU|Manifest: NOSIGNATURE CMDCam_FORGE_v2.1.1_mc1.20.1.jar |CMDCam |cmdcam |2.1.1 |SIDED_SETU|Manifest: NOSIGNATURE CreativeCore_FORGE_v2.11.25_mc1.20.1.jar |CreativeCore |creativecore |2.11.25 |SIDED_SETU|Manifest: NOSIGNATURE spectrelib-forge-0.13.14+1.20.1.jar |SpectreLib |spectrelib |0.13.14+1.20.1 |SIDED_SETU|Manifest: NOSIGNATURE supermartijn642corelib-1.1.17-forge-mc1.20.1.jar |SuperMartijn642's Core Lib |supermartijn642corelib |1.1.17 |SIDED_SETU|Manifest: NOSIGNATURE fairylights-7.0.0-1.20.1.jar |Fairy Lights |fairylights |7.0.0 |SIDED_SETU|Manifest: NOSIGNATURE born_in_chaos_[Forge]1.20.1_1.2.jar |Born in Chaos |born_in_chaos_v1 |1.0.0 |SIDED_SETU|Manifest: NOSIGNATURE portablemobs-1.2.0-forge-mc1.20.jar |Portable Mobs |portablemobs |1.2.0 |SIDED_SETU|Manifest: NOSIGNATURE L_Enders_Cataclysm-1.90 -1.20.1.jar |Cataclysm Mod |cataclysm |1.0 |SIDED_SETU|Manifest: NOSIGNATURE curios-forge-5.7.0+1.20.1.jar |Curios API |curios |5.7.0+1.20.1 |SIDED_SETU|Manifest: NOSIGNATURE oculus-mc1.20.1-1.6.9.jar |Oculus |oculus |1.6.9 |SIDED_SETU|Manifest: NOSIGNATURE gravestone-forge-1.20.1-1.0.14.jar |Gravestone Mod |gravestone |1.20.1-1.0.14 |SIDED_SETU|Manifest: NOSIGNATURE camera-1.20.1-1.0.6.jar |Camera Mod |camera |1.20.1-1.0.6 |SIDED_SETU|Manifest: NOSIGNATURE simplehats-forge-1.20.1-0.3.0.jar |SimpleHats |simplehats |1.20.1-0.3.0 |ERROR |Manifest: NOSIGNATURE polymorph-forge-0.49.2+1.20.1.jar |Polymorph |polymorph |0.49.2+1.20.1 |SIDED_SETU|Manifest: NOSIGNATURE bettervillage-forge-1.20.1-3.2.0.jar |Better village |bettervillage |3.1.0 |SIDED_SETU|Manifest: NOSIGNATURE resourcefullib-forge-1.20.1-2.1.23.jar |Resourceful Lib |resourcefullib |2.1.23 |SIDED_SETU|Manifest: NOSIGNATURE coroutil-forge-1.20.1-1.3.7.jar |CoroUtil |coroutil |1.20.1-1.3.7 |SIDED_SETU|Manifest: NOSIGNATURE fennecfox-forge-1.20.1-1.0.0.jar |Fennec Fox |fennecfox |1.0.0 |SIDED_SETU|Manifest: NOSIGNATURE cfm-forge-1.20.1-7.0.0-pre36.jar |MrCrayfish's Furniture Mod |cfm |7.0.0-pre36 |SIDED_SETU|Manifest: 0d:78:5f:44:c0:47:0c:8c:e2:63:a3:04:43:d4:12:7d:b0:7c:35:37:dc:40:b1:c1:98:ec:51:eb:3b:3c:45:99 architectury-9.2.14-forge.jar |Architectury |architectury |9.2.14 |SIDED_SETU|Manifest: NOSIGNATURE otyacraftengine-forge-mc1.20-3.7.0-alpha.2.jar |Otyacraft Engine |otyacraftengine |3.7.0-alpha.2 |SIDED_SETU|Manifest: NOSIGNATURE doapi-1.2.8-forge.jar |Lets Do Api |doapi |1.2.8 |SIDED_SETU|Manifest: NOSIGNATURE letsdo-bakery-forge-1.1.3b.jar |Bakery |bakery |1.1.3 |SIDED_SETU|Manifest: NOSIGNATURE letsdo-vinery-forge-1.4.11.jar |Vinery |vinery |1.4.11 |SIDED_SETU|Manifest: NOSIGNATURE letsdo-beachparty-forge-1.1.3.jar |Beachparty |beachparty |1.1.3 |SIDED_SETU|Manifest: NOSIGNATURE iammusicplayer-forge-mc1.20-3.22.0-alpha.3.jar |Iam Music Player |iammusicplayer |3.22.0-alpha.3 |SIDED_SETU|Manifest: NOSIGNATURE letsdo-brewery-forge-1.1.4.jar |Brewery |brewery |1.1.4 |SIDED_SETU|Manifest: NOSIGNATURE appleskin-forge-mc1.20.1-2.5.1.jar |AppleSkin |appleskin |2.5.1+mc1.20.1 |SIDED_SETU|Manifest: NOSIGNATURE mcw-furniture-3.2.2-mc1.20.1forge.jar |Macaw's Furniture |mcwfurnitures |3.2.2 |SIDED_SETU|Manifest: NOSIGNATURE justzoom_forge_1.0.2_MC_1.20.1.jar |Just Zoom |justzoom |1.0.2 |SIDED_SETU|Manifest: NOSIGNATURE JadeAddons-1.20.1-forge-5.2.2.jar |Jade Addons |jadeaddons |5.2.2 |SIDED_SETU|Manifest: NOSIGNATURE cosmeticarmorreworked-1.20.1-v1a.jar |CosmeticArmorReworked |cosmeticarmorreworked |1.20.1-v1a |SIDED_SETU|Manifest: 5e:ed:25:99:e4:44:14:c0:dd:89:c1:a9:4c:10:b5:0d:e4:b1:52:50:45:82:13:d8:d0:32:89:67:56:57:01:53 expandability-forge-9.0.0.jar |ExpandAbility |expandability |9.0.0 |SIDED_SETU|Manifest: NOSIGNATURE Crash Report UUID: 2f8745fa-ecf9-4392-858b-ff3869586f43 FML: 47.2 Forge: net.minecraftforge:47.2.21

**Comment by fonnymunkey** [comment]
Your Curios is outdated for what SimpleHats uses, either update Curios or wait for the pack developer to do it.
