### ISSUE TITLE
1.19.2 Forge hat bag wont open

### ISSUE THREAD

**Issue by alex-con-ruiz** [fonnymunkey/SimpleHats#8]
![2022-09-11_17 33 44](https://user-images.githubusercontent.com/73907482/189547829-854c9fec-07dd-4583-aa17-ff88bc53df5f.png)

Right click wont open bags

Forge 4.3.1.3 
Mincraft 1.19.2
SimpleHats simplehats-forge-1.19.2-0.1.5.jar
Curious  curios-forge-1.19.2-5.1.1.0.jar
Cloth  Conf cloth-config-8.0.75-forge.jar

JFYI

**Comment by fonnymunkey** [comment]
I'm able to open the bags just fine on matching versions. Are you holding right-click for a second or two, or just clicking? Otherwise its possible its a mod conflict.

**Comment by alex-con-ruiz** [comment]
I'm gonna retry, if this does not work im gonna check mod by mod, and if its a mod conflict i'll tell you at least.

**Comment by f0kx** [comment]
i also cant open it in 1.19.2

EDIT: Hold rightclick till you can open it ... i hold my rightclick and after a few millisecs i get a hat! XD

**Comment by fonnymunkey** [comment]
I'll probably add a tooltip or some particle effects to make it more apparent you have to hold to open.
