### ISSUE TITLE
i dont have the new hats

### ISSUE THREAD

**Issue by Papu010101100** [fonnymunkey/SimpleHats#80]
![imagen_2024-07-30_081239835](https://github.com/user-attachments/assets/d46ea4e3-7b0e-4b15-873a-9e1e00a1bf35)
I don't know why but in my world I don't have the same number of hats that I have in a new world that I have created, which has Cthulhus and Vateres, I have reviewed the versions of the mod and the complementary ones and they are updated and are the same version 1.20 .1, does anyone know why?

**Comment by fonnymunkey** [comment]
When you update the mod in a pack past a major version, the changelog notes on the version warn you you need to reset the simplehats.json file in the config folder in order for new hats to appear.
Delete simplehats.json and let it regenerate and the new hats will show up if the mod is updated.
