### ISSUE TITLE
Server Bug

### ISSUE THREAD

**Issue by EllensFish** [fonnymunkey/SimpleHats#81]
For some reason, when trying to join a server the mod states mismatched mod versions. Both server and player have the latest versions.  1.20.1

**Comment by fonnymunkey** [comment]
When either a server or client updates the mod past a major version, you need to delete the simplehats.json file in the config folder to regenerate it to get new hats, the changelogs warn about this.
If you are getting mismatched version warnings, that means either the server or the client or both are using old simplehat.json files, shut down the server/client and delete that file on both.
