### ISSUE TITLE
I cant open the bags

### ISSUE THREAD

**Issue by cruiz16** [fonnymunkey/SimpleHats#9]
Im trying to use your mod, but.. I cant open bags in creativa, survival, anything.. Im using Fabric 0.58.0 in a 1.18.2 minecraft versión

**Comment by cruiz16** [comment]
give a video with the issue :) [https://we.tl/t-vbOT95AVL5](url)

**Comment by fonnymunkey** [comment]
You need to hold right-click, not just right-click.

**Comment by fonnymunkey** [comment]
0.1.6 removes hold-to-open from hat bags, since it seems it just caused too much confusion and issues.
