### ISSUE TITLE
MisMatch error with my friend

### ISSUE THREAD

**Issue by JaxOfSpades21** [fonnymunkey/SimpleHats#90]
We have the mod in our modpack for fabric and he keeps getting a mismatch error. we have the same version for fabric, havent messed with the code. we have deleted and re downloaded it multiple times but he still gets mismatch errors. we specifically download the fabric 1.20.1 version. whats weird is that i can join him but he cant join me. my other friend is able to join me but not he isnt able to join me. not sure if it matters but hes on windows 11 while we are on windows 10. Normally he could just host but the world runs better on my pc and we really like the mod.

**Comment by fonnymunkey** [comment]
The simplehats json file in the config folder was either created on an older version for either the server or client, or it was modified. If you modified the json, make sure it matches on all sides, otherwise just delete the file and let it regenerate to defaults.
